-- id                               int                              子弹ID
-- prefabPath                       string                           子弹路径
-- trailPath                        string                           子弹轨迹路径
-- attackFilePath                   string                           攻击帧配置文件
-- camp                             int                              阵营
-- lockTarget                       int                              目标锁定方式
-- lockTargetParams                 tableString[k:#seq|v:#1(string)]   目标锁定参数
-- isPatrol                         bool                             巡逻开关
-- radius                           fixedint                         碰撞球半径
-- spaceRadius                      fixedfloat                       极闪距离
-- warningset                       string                           预警特效路径
-- moveSetting                      dict[14]                         运动设置
--    type                          string                           运动方式
--    speed                         fixedint                         速度
--    addSpeed                      fixedint                         加速度
--    gravity                       fixedint                         重力
--    length                        fixedint                         距离
--    params                        tableString[k:#seq|v:#1(string)]   附加参数
--    reflect                       bool                             环境反射
--    reflectLoss                   fixedfloat                       反射损耗
--    block                         bool                             环境阻挡
--    blockEffect                   string                           阻挡特效
--    checkRadius                   fixedfloat                       检测半径
--    trigger                       int                              移动停止后
--    triggerParams                 tableString[k:#seq|v:#1(string)]   移动停止后-扩展参数
--    endEffect                     string                           移动特效
-- hitSetting                       dict[7]                          碰撞设置
--    trigger                       int                              碰撞目标后
--    triggerParams                 tableString[k:#seq|v:#1(string)]   碰撞目标后操作参数
--    isDamage                      bool                             产生伤害
--    damageCD                      fixedint                         伤害倒计时
--    damageRange                   tableString[k:#seq|v:#1(int)]    伤害值(临时)
--    damageRadius                  fixedfloat                       伤害半径
--    damageDestroy                 bool                             伤害后是否销毁
-- patrolSetting                    dict[6]                          巡逻设置
--    radius                        fixedfloat                       巡逻半径
--    targetType                    int                              目标类型
--    targetParams                  tableString[k:#seq|v:#1(string)]   目标参数（预留）
--    triggerDelay                  fixedfloat                       触发延时（秒）
--    trigger                       int                              找到目标后
--    triggerParams                 tableString[k:#seq|v:#1(string)]   找到目标后-扩展参数

return {
	[1] = {
		id = 1,
		prefabPath = "Cube",
		trailPath = "",
		attackFilePath = "test",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 31457280 --[[30]],
			addSpeed = 104858 --[[0.1]],
			gravity = 0 --[[0]],
			length = 20971520 --[[20]],
			params = nil,
			reflect = false,
			reflectLoss = 0 --[[0]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[2] = {
		id = 2,
		prefabPath = "Cube",
		trailPath = "",
		attackFilePath = "test",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 31457280 --[[30]],
			addSpeed = 104858 --[[0.1]],
			gravity = 0 --[[0]],
			length = 20971520 --[[20]],
			params = nil,
			reflect = false,
			reflectLoss = 0 --[[0]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = false,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[3] = {
		id = 3,
		prefabPath = "Sphere",
		trailPath = "",
		attackFilePath = "test",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 20971520 --[[20]],
			addSpeed = 0 --[[0]],
			gravity = 20971520 --[[20]],
			length = 36700160 --[[35]],
			params = nil,
			reflect = true,
			reflectLoss = 209716 --[[0.2]],
			block = true,
			blockEffect = "",
			checkRadius = 314573 --[[0.3]],
			trigger = 10,
			triggerParams = {
				[1] = "4",
			},
			endEffect = "",
		},
		hitSetting = {
			trigger = 10,
			triggerParams = {
				[1] = "4",
			},
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 50,
				[2] = 100,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = false,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[4] = {
		id = 4,
		prefabPath = "Sphere",
		trailPath = "",
		attackFilePath = "test",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Falling",
			speed = 10485760 --[[10]],
			addSpeed = 0 --[[0]],
			gravity = 10485760 --[[10]],
			length = 20971520 --[[20]],
			params = nil,
			reflect = false,
			reflectLoss = 104858 --[[0.1]],
			block = true,
			blockEffect = "",
			checkRadius = 314573 --[[0.3]],
			trigger = 2,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 2097152 --[[2]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 5242880 --[[5]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[5] = {
		id = 5,
		prefabPath = "Cube",
		trailPath = "",
		attackFilePath = "test",
		camp = 1,
		lockTarget = 1,
		lockTargetParams = {
			[1] = "1",
		},
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Tracking",
			speed = 15728640 --[[15]],
			addSpeed = 209716 --[[0.2]],
			gravity = 0 --[[0]],
			length = 104857600 --[[100]],
			params = {
				[1] = "10",
			},
			reflect = false,
			reflectLoss = fixed.zero,
			block = true,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 2,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 1048576 --[[1]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[6] = {
		id = 6,
		prefabPath = "Cube",
		trailPath = "",
		attackFilePath = "test",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 41943040 --[[40]],
			addSpeed = 104858 --[[0.1]],
			gravity = 0 --[[0]],
			length = 209715200 --[[200]],
			params = nil,
			reflect = true,
			reflectLoss = 104858 --[[0.1]],
			block = true,
			blockEffect = "",
			checkRadius = 209716 --[[0.2]],
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[7] = {
		id = 7,
		prefabPath = "Sphere",
		trailPath = "",
		attackFilePath = "test",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = true,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 8388608 --[[8]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 52428800 --[[50]],
			params = nil,
			reflect = false,
			reflectLoss = 262144 --[[0.25]],
			block = true,
			blockEffect = "",
			checkRadius = 209716 --[[0.2]],
			trigger = 2,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 1048576 --[[1]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = 5242880 --[[5]],
			targetType = 0,
			targetParams = nil,
			triggerDelay = 1048576 --[[1]],
			trigger = 10,
			triggerParams = {
				[1] = "8",
			},
		},
	},
	[8] = {
		id = 8,
		prefabPath = "Sphere",
		trailPath = "",
		attackFilePath = "test",
		camp = 1,
		lockTarget = 1,
		lockTargetParams = {
			[1] = "1",
		},
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Tracking",
			speed = 15728640 --[[15]],
			addSpeed = 209716 --[[0.2]],
			gravity = 10485760 --[[10]],
			length = 31457280 --[[30]],
			params = {
				[1] = "10",
			},
			reflect = false,
			reflectLoss = 262144 --[[0.25]],
			block = true,
			blockEffect = "",
			checkRadius = 209716 --[[0.2]],
			trigger = 2,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 1048576 --[[1]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[9] = {
		id = 9,
		prefabPath = "Sphere",
		trailPath = "",
		attackFilePath = "test",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 10485760 --[[10]],
			addSpeed = 0 --[[0]],
			gravity = 10485760 --[[10]],
			length = 20971520 --[[20]],
			params = nil,
			reflect = true,
			reflectLoss = 262144 --[[0.25]],
			block = true,
			blockEffect = "",
			checkRadius = 209716 --[[0.2]],
			trigger = 2,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 1048576 --[[1]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[10] = {
		id = 10,
		prefabPath = "Bullet/Prefab/Ice_Bullet_01",
		trailPath = "Bullet/Prefab/Ice_Bullet_01_Trail",
		attackFilePath = "Ice_Bullet_01",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 41943040 --[[40]],
			addSpeed = 209716 --[[0.2]],
			gravity = 0 --[[0]],
			length = 15728640 --[[15]],
			params = nil,
			reflect = false,
			reflectLoss = 0 --[[0]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = false,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[11] = {
		id = 11,
		prefabPath = "Bullet/Prefab/Ice_Bullet_02",
		trailPath = "Bullet/Prefab/Ice_Bullet_02_Trail",
		attackFilePath = "Ice_Bullet_02",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 41943040 --[[40]],
			addSpeed = 209716 --[[0.2]],
			gravity = 0 --[[0]],
			length = 15728640 --[[15]],
			params = nil,
			reflect = false,
			reflectLoss = 0 --[[0]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = false,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[12] = {
		id = 12,
		prefabPath = "Bullet/Prefab/M_DEM_21101_skill_1_Bullet",
		trailPath = "",
		attackFilePath = "Monster_Bullet_21101_Skill01",
		camp = 1,
		lockTarget = 1,
		lockTargetParams = {
			[1] = "3",
		},
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = 2097152 --[[2]],
		warningset = "Warning/M_DEM_21101/Skill04_Bullet_Warning",
		moveSetting = {
			type = "Tracking",
			speed = 12582912 --[[12]],
			addSpeed = 0 --[[0]],
			gravity = 10485760 --[[10]],
			length = 104857600 --[[100]],
			params = {
				[1] = "10",
			},
			reflect = false,
			reflectLoss = 1048576 --[[1]],
			block = false,
			blockEffect = "",
			checkRadius = 209716 --[[0.2]],
			trigger = 2,
			triggerParams = nil,
			endEffect = "Effect/M_DEM_21101/M_DEM_21101_skill_2_Exploded",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 2621440 --[[2.5]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[13] = {
		id = 13,
		prefabPath = "Bullet/Prefab/M_DEM_21101_skill_3_Bullet",
		trailPath = "",
		attackFilePath = "Monster_Bullet_21101_Skill03",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 104857600 --[[100]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 20971520 --[[20]],
			params = nil,
			reflect = false,
			reflectLoss = 0 --[[0]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[14] = {
		id = 14,
		prefabPath = "Bullet/Prefab/B_30101_MSkill_4_1",
		trailPath = "",
		attackFilePath = "B_30101_MSkill_4",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 20971520 --[[20]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 20971520 --[[20]],
			params = nil,
			reflect = false,
			reflectLoss = 0 --[[0]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[15] = {
		id = 15,
		prefabPath = "Bullet/Prefab/B_30101_MSkill_4_2",
		trailPath = "",
		attackFilePath = "B_30101_MSkill_4",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 20971520 --[[20]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 20971520 --[[20]],
			params = nil,
			reflect = false,
			reflectLoss = 0 --[[0]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[16] = {
		id = 16,
		prefabPath = "Bullet/Prefab/B_30101_MSkill_4_3",
		trailPath = "",
		attackFilePath = "B_30101_MSkill_4",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 20971520 --[[20]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 20971520 --[[20]],
			params = nil,
			reflect = false,
			reflectLoss = 0 --[[0]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 0 --[[0]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[17] = {
		id = 17,
		prefabPath = "Bullet/Prefab/M_DEM_21101_skill_3_Bullet",
		trailPath = "",
		attackFilePath = "Ice_Bullet_01",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 10485760 --[[10]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 41943040 --[[40]],
			params = {
				[1] = "10",
			},
			reflect = false,
			reflectLoss = 1048576 --[[1]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 2621440 --[[2.5]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[18] = {
		id = 18,
		prefabPath = "Bullet/Prefab/M_DEM_21101_skill_1_Bullet",
		trailPath = "",
		attackFilePath = "Ice_Bullet_01",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 5242880 --[[5]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 41943040 --[[40]],
			params = {
				[1] = "10",
			},
			reflect = false,
			reflectLoss = 1048576 --[[1]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 2621440 --[[2.5]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[19] = {
		id = 19,
		prefabPath = "Bullet/Prefab/M_DEM_21101_skill_1_Bullet",
		trailPath = "",
		attackFilePath = "Ice_Bullet_01",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 10485760 --[[10]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 41943040 --[[40]],
			params = {
				[1] = "10",
			},
			reflect = false,
			reflectLoss = 1048576 --[[1]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 2621440 --[[2.5]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[20] = {
		id = 20,
		prefabPath = "Bullet/Prefab/M_DEM_21101_skill_1_Bullet",
		trailPath = "",
		attackFilePath = "Ice_Bullet_01",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 5242880 --[[5]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 41943040 --[[40]],
			params = {
				[1] = "10",
			},
			reflect = false,
			reflectLoss = 1048576 --[[1]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 2621440 --[[2.5]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
	[21] = {
		id = 21,
		prefabPath = "Bullet/Prefab/M_DEM_21101_skill_3_Bullet",
		trailPath = "",
		attackFilePath = "Ice_Bullet_01",
		camp = 1,
		lockTarget = nil,
		lockTargetParams = nil,
		isPatrol = false,
		radius = 209716 --[[0.2]],
		spaceRadius = fixed.zero,
		warningset = "",
		moveSetting = {
			type = "Linear",
			speed = 5242880 --[[5]],
			addSpeed = 0 --[[0]],
			gravity = 0 --[[0]],
			length = 41943040 --[[40]],
			params = {
				[1] = "10",
			},
			reflect = false,
			reflectLoss = 1048576 --[[1]],
			block = false,
			blockEffect = "",
			checkRadius = fixed.zero,
			trigger = 1,
			triggerParams = nil,
			endEffect = "",
		},
		hitSetting = {
			trigger = nil,
			triggerParams = nil,
			isDamage = true,
			damageCD = 0 --[[0]],
			damageRange = {
				[1] = 200,
				[2] = 600,
			},
			damageRadius = 2621440 --[[2.5]],
			damageDestroy = true,
		},
		patrolSetting = {
			radius = fixed.zero,
			targetType = nil,
			targetParams = nil,
			triggerDelay = fixed.zero,
			trigger = nil,
			triggerParams = nil,
		},
	},
}
