-- id                               int                              关卡ID
-- type                             int                              关卡类型
-- hero_type                        int                              阵容类型
-- hero_limit                       tableString[k:#2(int)|v:#table(id=#1(int),count=#2(int))]   限定精灵信息
-- capter                           int                              所属章节
-- dungeon_name                     lang                             关卡名称（仅客户端用）
-- dungeon_desc                     lang                             关卡描述
-- icon_path                        string                           关卡图标
-- monster_level                    int                              关卡怪物等级
-- dungeon_script                   int                              脚本ID
-- attack_mode                      int                              攻击模式ID
-- time                             int                              关卡时长(秒)
-- map_id                           int                              关联地图信息
-- is_runfast                       bool                             是否使用快跑模式
-- terrain_script                   string                           地形配置脚本
-- is_drop                          bool                             是否掉落

return {
	[10001] = {
		id = 10001,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "木桩训练",
		dungeon_desc = "",
		icon_path = "001",
		monster_level = 1,
		dungeon_script = 10021,
		attack_mode = 1,
		time = 300,
		map_id = nil,
		is_runfast = false,
		terrain_script = "config/terrain/Demo01",
		is_drop = true,
	},
	[10002] = {
		id = 10002,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "对战训练",
		dungeon_desc = "",
		icon_path = "002",
		monster_level = 1,
		dungeon_script = 10022,
		attack_mode = 1,
		time = 300,
		map_id = nil,
		is_runfast = false,
		terrain_script = "config/terrain/Demo01",
		is_drop = true,
	},
	[10003] = {
		id = 10003,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "怪物测试",
		dungeon_desc = "",
		icon_path = "002",
		monster_level = 1,
		dungeon_script = 10006,
		attack_mode = 1,
		time = 300,
		map_id = nil,
		is_runfast = false,
		terrain_script = "config/terrain/Demo01",
		is_drop = true,
	},
	[10004] = {
		id = 10004,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "卡巴拉1号",
		dungeon_desc = "",
		icon_path = "002",
		monster_level = 1,
		dungeon_script = 10021,
		attack_mode = 1,
		time = 300,
		map_id = nil,
		is_runfast = false,
		terrain_script = "config/terrain/Demo01",
		is_drop = true,
	},
	[10005] = {
		id = 10005,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "完整关卡测试",
		dungeon_desc = "",
		icon_path = "002",
		monster_level = 1,
		dungeon_script = 10023,
		attack_mode = 1,
		time = 300,
		map_id = nil,
		is_runfast = false,
		terrain_script = "config/terrain/Demo01",
		is_drop = true,
	},
	[10006] = {
		id = 10006,
		type = 3,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "尼尔地图测试",
		dungeon_desc = "",
		icon_path = "002",
		monster_level = 1,
		dungeon_script = 10031,
		attack_mode = 1,
		time = 300,
		map_id = nil,
		is_runfast = true,
		terrain_script = "config/terrain/Room",
		is_drop = true,
	},
	[10007] = {
		id = 10007,
		type = 3,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "天台测试",
		dungeon_desc = "",
		icon_path = "002",
		monster_level = 1,
		dungeon_script = 10032,
		attack_mode = 1,
		time = 300,
		map_id = nil,
		is_runfast = true,
		terrain_script = "config/terrain/newRoom",
		is_drop = true,
	},
	[10008] = {
		id = 10008,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "木桩训练",
		dungeon_desc = "",
		icon_path = "001",
		monster_level = 1,
		dungeon_script = 10021,
		attack_mode = 1,
		time = 300,
		map_id = nil,
		is_runfast = false,
		terrain_script = "config/terrain/Demo01",
		is_drop = true,
	},
	[10009] = {
		id = 10009,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "NOAH研究中心",
		dungeon_desc = "NOAH，一座神秘的研究中心，进行着不为人知的生物研究。",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 21005,
		attack_mode = 1,
		time = nil,
		map_id = 2,
		is_runfast = false,
		terrain_script = "config/terrain/Room",
		is_drop = true,
	},
	[10010] = {
		id = 10010,
		type = 3,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "NOAH研究中心",
		dungeon_desc = "NOAH，一座神秘的研究中心，进行着不为人知的生物研究。",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 10028,
		attack_mode = 1,
		time = nil,
		map_id = 2,
		is_runfast = false,
		terrain_script = "config/terrain/Room",
		is_drop = true,
	},
	[10011] = {
		id = 10011,
		type = 3,
		hero_type = 1,
		hero_limit = nil,
		capter = nil,
		dungeon_name = "NOAH研究中心",
		dungeon_desc = "NOAH，一座神秘的研究中心，进行着不为人知的生物研究。",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 10028,
		attack_mode = 1,
		time = nil,
		map_id = 2,
		is_runfast = false,
		terrain_script = "config/terrain/Room",
		is_drop = true,
	},
	[201001] = {
		id = 201001,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = 10001,
		dungeon_name = "平民区",
		dungeon_desc = "平民区关卡描述",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 21001,
		attack_mode = 1,
		time = nil,
		map_id = 1,
		is_runfast = true,
		terrain_script = "",
		is_drop = true,
	},
	[201002] = {
		id = 201002,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = 10001,
		dungeon_name = "商业区",
		dungeon_desc = "在小城中心的商业区，失去了原来繁华喧闹的场面，一切都显得那么诡异。",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 21002,
		attack_mode = 1,
		time = nil,
		map_id = 1,
		is_runfast = true,
		terrain_script = "",
		is_drop = true,
	},
	[201003] = {
		id = 201003,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = 10001,
		dungeon_name = "NOAH研究中心",
		dungeon_desc = "NOAH，一座神秘的研究中心，进行着不为人知的生物研究。",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 21003,
		attack_mode = 1,
		time = nil,
		map_id = 2,
		is_runfast = true,
		terrain_script = "",
		is_drop = true,
	},
	[201004] = {
		id = 201004,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = 10001,
		dungeon_name = "NOAH顶层",
		dungeon_desc = "NOAH大楼的顶层，发现这一切的起源之地，似乎存在着什么恐怖强大的力量。",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 21004,
		attack_mode = 1,
		time = nil,
		map_id = 3,
		is_runfast = true,
		terrain_script = "",
		is_drop = true,
	},
	[201005] = {
		id = 201005,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = 10001,
		dungeon_name = "天台-2",
		dungeon_desc = "天台-2描述",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 21005,
		attack_mode = 1,
		time = nil,
		map_id = 4,
		is_runfast = true,
		terrain_script = "",
		is_drop = true,
	},
	[202001] = {
		id = 202001,
		type = 3,
		hero_type = 1,
		hero_limit = nil,
		capter = 30001,
		dungeon_name = "NOAH研究中心",
		dungeon_desc = "NOAH，一座神秘的研究中心，进行着不为人知的生物研究。",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 10028,
		attack_mode = 1,
		time = nil,
		map_id = nil,
		is_runfast = false,
		terrain_script = "",
		is_drop = true,
	},
	[202002] = {
		id = 202002,
		type = 1,
		hero_type = 1,
		hero_limit = nil,
		capter = 10002,
		dungeon_name = "开放世界测试",
		dungeon_desc = "开放世界测试",
		icon_path = "level_001",
		monster_level = 1,
		dungeon_script = 21006,
		attack_mode = 1,
		time = nil,
		map_id = 3,
		is_runfast = false,
		terrain_script = "",
		is_drop = true,
	},
}
