-- id                               int                              道具ID
-- bag_id                           int                              所属背包
-- name                             lang                             道具名称
-- type1                            int                              道具大类
-- type2                            int                              道具子类
-- type3                            int                              道具细分
-- des                              lang                             道具描述
-- bg_des                           lang                             道具背景描述
-- item_tag                         int                              道具角标
-- item_icon                        int                              道具图标
-- item_bg                          int                              道具背板
-- quality                          int                              道具品质
-- star                             int                              道具星级
-- summax                           int                              获取上限
-- gridmax                          int                              堆叠上限
-- jump_id                          tableString[k:#seq|v:#table(jumpid=#1(int),count=#2(int))]   获取跳转
-- jump_des                         lang                             无获取途径描述
-- resolve_item                     tableString[k:#seq|v:#table(id=#1(int),count=#2(int))]   分解道具
-- is_resolve                       bool                             是否可手动分解
-- max_way                          int                              获取上限处理方式
-- autouse                          bool                             自使用
-- useprofit                        string                           自使用效果
-- show                             int                              获得方式展示
-- variable                         string                           关联参数
-- item_go                          tableString[k:#seq|v:#1(int)]    前往功能
-- star_max                         int                              道具星级上限
-- package_type                     int                              掉落类型
-- effect_id                        string                           掉落特效

return {
	[10101] = {
		id = 10101,
		bag_id = 0,
		name = "钻石",
		type1 = 1,
		type2 = 1,
		type3 = 1,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 3,
		quality = 3,
		star = 3,
		summax = 999999999,
		gridmax = 999999999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = true,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[101011] = {
		id = 101011,
		bag_id = 0,
		name = "付费钻石",
		type1 = 1,
		type2 = 1,
		type3 = 1,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 1,
		quality = 1,
		star = 1,
		summax = 999999999,
		gridmax = 999999999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = true,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[101012] = {
		id = 101012,
		bag_id = 0,
		name = "免费钻石",
		type1 = 1,
		type2 = 1,
		type3 = 1,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 1,
		quality = 1,
		star = 1,
		summax = 999999999,
		gridmax = 999999999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = true,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10102] = {
		id = 10102,
		bag_id = 0,
		name = "金币",
		type1 = 1,
		type2 = 1,
		type3 = 1,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 1,
		quality = 1,
		star = 1,
		summax = 999999999,
		gridmax = 999999999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 1,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = true,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10103] = {
		id = 10103,
		bag_id = 0,
		name = "金币",
		type1 = 1,
		type2 = 1,
		type3 = 1,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 1,
		quality = 1,
		star = 1,
		summax = 999999999,
		gridmax = 999999999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 1,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = true,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10201] = {
		id = 10201,
		bag_id = 3,
		name = "代币",
		type1 = 1,
		type2 = 2,
		type3 = 1,
		des = "代币道具描述",
		bg_des = "代币背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 2,
		quality = 2,
		star = 2,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10301] = {
		id = 10301,
		bag_id = 3,
		name = "门票",
		type1 = 1,
		type2 = 3,
		type3 = 1,
		des = "门票道具描述",
		bg_des = "门票背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 3,
		quality = 3,
		star = 3,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10401] = {
		id = 10401,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 4,
		quality = 4,
		star = 4,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10402] = {
		id = 10402,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 4,
		quality = 4,
		star = 4,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10501] = {
		id = 10501,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10502] = {
		id = 10502,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10503] = {
		id = 10503,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10504] = {
		id = 10504,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10505] = {
		id = 10505,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10506] = {
		id = 10506,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10507] = {
		id = 10507,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10601] = {
		id = 10601,
		bag_id = 5,
		name = "显示道具",
		type1 = 1,
		type2 = 6,
		type3 = 1,
		des = "显示道具描述",
		bg_des = "显示背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 1,
		quality = 1,
		star = 1,
		summax = 999,
		gridmax = 999,
		jump_id = nil,
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[10701] = {
		id = 10701,
		bag_id = 3,
		name = "经验类",
		type1 = 1,
		type2 = 7,
		type3 = 1,
		des = "经验类道具描述",
		bg_des = "经验类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 2,
		quality = 1,
		star = 2,
		summax = 999,
		gridmax = 999,
		jump_id = nil,
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104001] = {
		id = 104001,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 1,
		quality = 1,
		star = 1,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104002] = {
		id = 104002,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 2,
		quality = 2,
		star = 2,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104003] = {
		id = 104003,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 3,
		quality = 3,
		star = 3,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104004] = {
		id = 104004,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 4,
		quality = 4,
		star = 4,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104005] = {
		id = 104005,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 1,
		quality = 1,
		star = 1,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104006] = {
		id = 104006,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 2,
		quality = 2,
		star = 2,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104007] = {
		id = 104007,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 3,
		quality = 3,
		star = 3,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104008] = {
		id = 104008,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 1,
		quality = 1,
		star = 1,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104009] = {
		id = 104009,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 2,
		quality = 2,
		star = 2,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104010] = {
		id = 104010,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 3,
		quality = 3,
		star = 3,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104011] = {
		id = 104011,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 1,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[104012] = {
		id = 104012,
		bag_id = 3,
		name = "养成材料",
		type1 = 1,
		type2 = 4,
		type3 = 1,
		des = "养成道具描述",
		bg_des = "养成背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 2,
		quality = 6,
		star = 6,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053101] = {
		id = 1053101,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053102] = {
		id = 1053102,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053103] = {
		id = 1053103,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053104] = {
		id = 1053104,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053105] = {
		id = 1053105,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053106] = {
		id = 1053106,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053201] = {
		id = 1053201,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053202] = {
		id = 1053202,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053203] = {
		id = 1053203,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053204] = {
		id = 1053204,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053205] = {
		id = 1053205,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053206] = {
		id = 1053206,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053301] = {
		id = 1053301,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053302] = {
		id = 1053302,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053303] = {
		id = 1053303,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053304] = {
		id = 1053304,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053305] = {
		id = 1053305,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053306] = {
		id = 1053306,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053401] = {
		id = 1053401,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053402] = {
		id = 1053402,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053403] = {
		id = 1053403,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053404] = {
		id = 1053404,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053405] = {
		id = 1053405,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053406] = {
		id = 1053406,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053501] = {
		id = 1053501,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053502] = {
		id = 1053502,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053503] = {
		id = 1053503,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053504] = {
		id = 1053504,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053505] = {
		id = 1053505,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
	[1053506] = {
		id = 1053506,
		bag_id = 4,
		name = "碎片类",
		type1 = 1,
		type2 = 5,
		type3 = 1,
		des = "碎片类道具描述",
		bg_des = "碎片类背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		star_max = 5,
		package_type = 2,
		effect_id = "Effect/Common/sce_kaibaoxiang02",
	},
}
