-- id                               int                              特效id
-- effects                          dict[3]                          特效表现
--    execute                       string                           执行特效
--    continue                      string                           持续特效
--    disappear                     string                           消失特效
-- instead_lv                       tableString[k:#seq|v:#1(int)]    替换等级
-- check_points                     tableString[k:#seq|v:#1(int)]    检查点
-- chance                           fixedint                         检查概率
-- conditions                       dict[3]                          检查条件
--    condition1                    tableString[k:#seq|v:#1(fixedfloat)]   条件一
--    condition2                    tableString[k:#seq|v:#1(fixedfloat)]   条件二
--    condition3                    tableString[k:#seq|v:#1(fixedfloat)]   条件三
-- range                            tableString[k:#seq|v:#1(fixedfloat)]   目标选择
-- delay                            int                              延迟施放
-- type                             int                              特效类型
-- type_sub                         int                              类型子类
-- type_content                     tableString[k:#seq|v:#1(fixedint)]   类型具体内容
-- parameter1                       tableString[k:#seq|v:#1(fixedfloat)]   特殊参数1
-- parameter2                       tableString[k:#seq|v:#1(fixedfloat)]   特殊参数2
-- parameter3                       tableString[k:#seq|v:#1(fixedfloat)]   特殊参数3
-- buff_icon                        string                           buff图标
-- turn                             tableString[k:#seq|v:#1(fixedfloat)]   持续时间
-- number                           tableString[k:#seq|v:#1(fixedfloat)]   次数持续
-- tags                             tableString[k:#seq|v:#1(int)]    标签

return {
	[300011] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 104857600 --[[100]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[300021] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 104857600 --[[100]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[300031] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 104857600 --[[100]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[300061] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 41943040 --[[40]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[300041] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 104857600 --[[100]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[300051] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 104857600 --[[100]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[300081] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 104857600 --[[100]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[300101] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 104857600 --[[100]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[300111] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 104857600 --[[100]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[300121] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 104857600 --[[100]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[400011] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 20971520 --[[20]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[400021] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 26214400 --[[25]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[400031] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 26214400 --[[25]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[400041] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 31457280 --[[30]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[400051] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 157286400 --[[150]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[400061] = {
		effects = {
			execute = "Effect/Monster/B_30101/B_30101_Skill_3",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 8,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = {
				[1] = 0 --[[0]],
				[2] = 24117248 --[[23]],
			},
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 0 --[[0]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = 300,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 0 --[[0]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[400062] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 8,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = {
				[1] = 0 --[[0]],
				[2] = 24117248 --[[23]],
			},
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 0 --[[0]],
			[2] = 524288000 --[[500]],
			[3] = 1048576 --[[1]],
		},
		delay = 390,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 209715200 --[[200]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[410011] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 26214400 --[[25]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[410021] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 31457280 --[[30]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[410031] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 31457280 --[[30]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[410041] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 41943040 --[[40]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[410051] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 1048576 --[[1]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 125829120 --[[120]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[410061] = {
		effects = {
			execute = "Effect/Monster/B_30101/B_30101_Skill_3",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 8,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = {
				[1] = 0 --[[0]],
				[2] = 24117248 --[[23]],
			},
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 0 --[[0]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 0 --[[0]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[410062] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 8,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = {
				[1] = 0 --[[0]],
				[2] = 24117248 --[[23]],
			},
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 0 --[[0]],
			[2] = 524288000 --[[500]],
			[3] = 1048576 --[[1]],
		},
		delay = 100,
		type = 10,
		type_sub = nil,
		type_content = {
			[1] = 314572800 --[[300]],
			[2] = 0 --[[0]],
		},
		parameter1 = nil,
		parameter2 = nil,
		parameter3 = nil,
		buff_icon = "",
		turn = nil,
		number = nil,
		tags = nil,
	},
	[410063] = {
		effects = {
			execute = "",
			continue = "",
			disappear = "",
		},
		instead_lv = nil,
		check_points = {
			[1] = 0,
		},
		chance = 104857600 --[[100]],
		conditions = {
			condition1 = nil,
			condition2 = nil,
			condition3 = nil,
		},
		range = {
			[1] = 0 --[[0]],
			[2] = 0 --[[0]],
			[3] = 0 --[[0]],
		},
		delay = nil,
		type = 1004,
		type_sub = nil,
		type_content = nil,
		parameter1 = {
			[1] = 342884352 --[[327]],
			[2] = 0 --[[0]],
		},
		parameter2 = {
			[1] = 0 --[[0]],
			[2] = 0 --[[0]],
		},
		parameter3 = nil,
		buff_icon = "",
		turn = {
			[1] = 342884352 --[[327]],
			[2] = 0 --[[0]],
			[3] = 342884352 --[[327]],
			[4] = 0 --[[0]],
		},
		number = nil,
		tags = {
			[1] = 999,
			[2] = 1,
		},
	},
}
