-- id                               int                              道具ID
-- bag_id                           int                              所属背包
-- name                             lang                             道具名称
-- type1                            int                              道具大类
-- type2                            int                              道具子类
-- type3                            int                              道具细分
-- chip                             int                              对应碎片id
-- chip_num                         int                              合成所需数量
-- des                              lang                             道具描述
-- bg_des                           lang                             道具背景描述
-- item_tag                         int                              道具角标
-- item_icon                        int                              道具图标
-- item_bg                          int                              道具背板
-- quality                          int                              道具品质
-- star                             int                              道具星级
-- default_star                     int                              初始星级
-- summax                           int                              获取上限
-- gridmax                          int                              堆叠上限
-- jump_id                          tableString[k:#seq|v:#table(jumpid=#1(int),count=#2(int))]   获取跳转
-- jump_des                         lang                             无获取途径描述
-- resolve_item                     tableString[k:#seq|v:#table(id=#1(int),count=#2(int))]   分解道具
-- is_resolve                       bool                             是否可手动分解
-- max_way                          int                              获取上限处理方式
-- autouse                          bool                             自使用
-- useprofit                        string                           自使用效果
-- show                             int                              获得方式展示
-- variable                         string                           关联参数
-- item_go                          tableString[k:#seq|v:#1(int)]    前往功能

return {
	[403101] = {
		id = 403101,
		bag_id = 11,
		name = "钻石",
		type1 = 4,
		type2 = 3,
		type3 = 1,
		chip = 1053101,
		chip_num = 10,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 1,
		quality = 1,
		star = 1,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403102] = {
		id = 403102,
		bag_id = 11,
		name = "金币",
		type1 = 4,
		type2 = 3,
		type3 = 1,
		chip = 1053102,
		chip_num = 11,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 2,
		quality = 2,
		star = 2,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403103] = {
		id = 403103,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 1,
		chip = 1053103,
		chip_num = 12,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 3,
		quality = 3,
		star = 3,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403104] = {
		id = 403104,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 1,
		chip = 1053104,
		chip_num = 13,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 4,
		quality = 4,
		star = 4,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 1,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403105] = {
		id = 403105,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 1,
		chip = 1053105,
		chip_num = 14,
		des = "代币道具描述",
		bg_des = "代币背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403106] = {
		id = 403106,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 1,
		chip = 1053106,
		chip_num = 15,
		des = "门票道具描述",
		bg_des = "门票背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 6,
		star = 6,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403201] = {
		id = 403201,
		bag_id = 11,
		name = "钻石",
		type1 = 4,
		type2 = 3,
		type3 = 2,
		chip = 1053201,
		chip_num = 10,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 1,
		quality = 1,
		star = 1,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403202] = {
		id = 403202,
		bag_id = 11,
		name = "金币",
		type1 = 4,
		type2 = 3,
		type3 = 2,
		chip = 1053202,
		chip_num = 11,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 2,
		quality = 2,
		star = 2,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403203] = {
		id = 403203,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 2,
		chip = 1053203,
		chip_num = 12,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 3,
		quality = 3,
		star = 3,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403204] = {
		id = 403204,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 2,
		chip = 1053204,
		chip_num = 13,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 4,
		quality = 4,
		star = 4,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 1,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403205] = {
		id = 403205,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 2,
		chip = 1053205,
		chip_num = 14,
		des = "代币道具描述",
		bg_des = "代币背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403206] = {
		id = 403206,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 2,
		chip = 1053206,
		chip_num = 15,
		des = "门票道具描述",
		bg_des = "门票背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 6,
		star = 6,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403301] = {
		id = 403301,
		bag_id = 11,
		name = "钻石",
		type1 = 4,
		type2 = 3,
		type3 = 3,
		chip = 1053301,
		chip_num = 10,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 1,
		quality = 1,
		star = 1,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403302] = {
		id = 403302,
		bag_id = 11,
		name = "金币",
		type1 = 4,
		type2 = 3,
		type3 = 3,
		chip = 1053302,
		chip_num = 11,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 2,
		quality = 2,
		star = 2,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403303] = {
		id = 403303,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 3,
		chip = 1053303,
		chip_num = 12,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 3,
		quality = 3,
		star = 3,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403304] = {
		id = 403304,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 3,
		chip = 1053304,
		chip_num = 13,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 4,
		quality = 4,
		star = 4,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 1,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403305] = {
		id = 403305,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 3,
		chip = 1053305,
		chip_num = 14,
		des = "代币道具描述",
		bg_des = "代币背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403306] = {
		id = 403306,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 3,
		chip = 1053306,
		chip_num = 15,
		des = "门票道具描述",
		bg_des = "门票背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 6,
		star = 6,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403401] = {
		id = 403401,
		bag_id = 11,
		name = "钻石",
		type1 = 4,
		type2 = 3,
		type3 = 4,
		chip = 1053401,
		chip_num = 10,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 1,
		quality = 1,
		star = 1,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403402] = {
		id = 403402,
		bag_id = 11,
		name = "金币",
		type1 = 4,
		type2 = 3,
		type3 = 4,
		chip = 1053402,
		chip_num = 11,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 2,
		quality = 2,
		star = 2,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403403] = {
		id = 403403,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 4,
		chip = 1053403,
		chip_num = 12,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 3,
		quality = 3,
		star = 3,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403404] = {
		id = 403404,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 4,
		chip = 1053404,
		chip_num = 13,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 4,
		quality = 4,
		star = 4,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 1,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403405] = {
		id = 403405,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 4,
		chip = 1053405,
		chip_num = 14,
		des = "代币道具描述",
		bg_des = "代币背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403406] = {
		id = 403406,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 4,
		chip = 1053406,
		chip_num = 15,
		des = "门票道具描述",
		bg_des = "门票背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 6,
		star = 6,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403501] = {
		id = 403501,
		bag_id = 11,
		name = "钻石",
		type1 = 4,
		type2 = 3,
		type3 = 5,
		chip = 1053501,
		chip_num = 10,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 1,
		quality = 1,
		star = 1,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403502] = {
		id = 403502,
		bag_id = 11,
		name = "金币",
		type1 = 4,
		type2 = 3,
		type3 = 5,
		chip = 1053502,
		chip_num = 11,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 2,
		quality = 2,
		star = 2,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403503] = {
		id = 403503,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 5,
		chip = 1053503,
		chip_num = 12,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 3,
		quality = 3,
		star = 3,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403504] = {
		id = 403504,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 5,
		chip = 1053504,
		chip_num = 13,
		des = "付费钻石",
		bg_des = "免费钻石",
		item_tag = nil,
		item_icon = 10001,
		item_bg = 4,
		quality = 4,
		star = 4,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 1,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403505] = {
		id = 403505,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 5,
		chip = 1053505,
		chip_num = 14,
		des = "代币道具描述",
		bg_des = "代币背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 5,
		star = 5,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
	[403506] = {
		id = 403506,
		bag_id = 11,
		name = "",
		type1 = 4,
		type2 = 3,
		type3 = 5,
		chip = 1053506,
		chip_num = 15,
		des = "门票道具描述",
		bg_des = "门票背景描述",
		item_tag = nil,
		item_icon = 10002,
		item_bg = 5,
		quality = 6,
		star = 6,
		default_star = 1,
		summax = 1,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
	},
}
