return
{
	["id"]=10008,
	["name"]="演示关卡",
	["groupName"]="Demo测试关卡",
	["playStartAnimation"]=true,
	["sceneName"]="Room.unity",
	["sceneFile"]="Assets/Scenes/Room.unity",
	["desc"]="",
	["borns"]={
		[1]={
			["uid"]="629368c3a66d40c1bf383acd808bee74",
			["transform"]=
			{
				["id"]=0,
				["name"]="",
				["position"]={["x"]=41.43,["y"]=0.64,["z"]=-1.844,},
				["scale"]={["x"]=1,["y"]=1,["z"]=1,},
				["rotation"]={["x"]=0,["y"]=0,["z"]=0,},
				["size"]={["x"]=1,["y"]=1,["z"]=1,},
			}
		},
	},
	["props"]={
	},
	["triggers"]={
		[1]={
			["id"]=3003,
			["enable"]=true,
			["unlimited"]=true,
			["desc"]="",
			["loopTimes"]=1,
			["reachConditionNum"]=0,
			["excuteNum"]=0,
			["triggerExecutType"]=2,
			["triggerNodes"]={
				[1]={
					["id"]="2702ea7226b045958283d7fd7b1758e0",
					["Type"]="Start",
					["enable"]=true,
					["time"]=0,
				},
			},
			["conditionNodes"]={
			},
			["executeNodes"]={
				[1]={
					["id"]="b4899ef7f83c4f2e84287d2316f88e26",
					["Type"]="ActorEnter",
					["enable"]=true,
				},
			}},
	},
}