-- id                               int                              id
-- type                             int                              任务类型
-- stronghold_task                  Int                              据点任务
-- name                             lang                             任务名称
-- desc                             lang                             任务描述
-- capter                           int                              任务所属章节ID
-- level_id                         int                              任务所属关卡ID（客户端）
-- scenes_pos                       tableString[k:#seq|v:#1(int)]    场景中任务位置（客户端）
-- scenes_radius                    tableString[k:#seq|v:#1(int)]    引导点半径
-- map_id                           int                              所属地图（客户端）
-- map_pos                          int                              地图坐标（客户端）
-- accept_type                      int                              接取方式
-- draw_type                        bool                             领取奖励方式
-- last_task_id                     int                              后置任务
-- level                            int                              接取任务等级
-- finish_type                      int                              完成任务条件类型
-- finish_param                     string                           完成任务条件参数
-- finish_num                       tableString[k:#seq|v:#1(int)]    完成任务条件数量
-- finish_desc                      lang                             完成任务条件描述
-- event                            int                              激活的关卡事件ID(客户端)
-- reward                           tableString[k:#1(int)|v:#table(id=#1(int),count=#2(int))]   任务奖励
-- is_ending                        bool                             是否为结算任务
-- lock_area                        int                              解锁的区域ID
-- lock_capter                      int                              解锁的章节ID
-- console_id                       tableString[k:#seq|v:#1(int)]    激活的操作台ID
-- obstacle_id                      tableString[k:#seq|v:#1(int)]    激活的障碍物ID
-- gate_id                          tableString[k:#seq|v:#1(int)]    激活的门ID

return {
	[20100102] = {
		id = 20100102,
		type = 1,
		stronghold_task = 0,
		name = "搜集情报",
		desc = "身处在一个陌生的区域，不管怎么说，先调查区域找到线索吧",
		capter = 10001,
		level_id = 201004,
		scenes_pos = {
			[1] = -40,
			[2] = 3,
			[3] = 39,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100103,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20004,
		},
		finish_desc = "查看第一处线索",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100103] = {
		id = 20100103,
		type = 1,
		stronghold_task = 0,
		name = "搜集情报",
		desc = "身处在一个陌生的区域，不管怎么说，先调查区域找到线索吧",
		capter = 10001,
		level_id = 201004,
		scenes_pos = {
			[1] = -26,
			[2] = 4,
			[3] = -6,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100104,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20024,
		},
		finish_desc = "查看第二处线索",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100104] = {
		id = 20100104,
		type = 1,
		stronghold_task = 0,
		name = "搜集情报",
		desc = "身处在一个陌生的区域，不管怎么说，先调查区域找到线索吧",
		capter = 10001,
		level_id = 201004,
		scenes_pos = {
			[1] = -39,
			[2] = 3,
			[3] = -53,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100105,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20005,
		},
		finish_desc = "查看第三处线索",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100105] = {
		id = 20100105,
		type = 1,
		stronghold_task = 0,
		name = "前往商业区",
		desc = "根据线索，如果要弄清楚这里发生的一起，我必须要前往线索中所说的商业区了。",
		capter = 10001,
		level_id = 201004,
		scenes_pos = {
			[1] = -61,
			[2] = 3,
			[3] = -43,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100106,
		level = 1,
		finish_type = 6,
		finish_param = "area",
		finish_num = {
			[1] = 20001,
		},
		finish_desc = "通过电梯前往商业区",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100106] = {
		id = 20100106,
		type = 1,
		stronghold_task = 0,
		name = "深入调查",
		desc = "商业区也是一副人迹寥寥的景象，我们看看能不能找出造成这种现象的原因吧！",
		capter = 10001,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100109,
		level = 1,
		finish_type = 1,
		finish_param = "subtask_sequence",
		finish_num = {
			[1] = 20100107,
			[2] = 20100108,
		},
		finish_desc = "",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100107] = {
		id = 20100107,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10001,
		level_id = 201002,
		scenes_pos = {
			[1] = -112,
			[2] = -17,
			[3] = -47,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = 20100108,
		level = 1,
		finish_type = 4,
		finish_param = "control_num",
		finish_num = {
			[1] = 2008,
			[2] = 1,
		},
		finish_desc = "调查商业区的事件1",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100108] = {
		id = 20100108,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10001,
		level_id = 201002,
		scenes_pos = {
			[1] = -133,
			[2] = -17,
			[3] = -6,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = nil,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20008,
		},
		finish_desc = "调查商业区的事件2",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100109] = {
		id = 20100109,
		type = 1,
		stronghold_task = 0,
		name = "神秘晶体",
		desc = "看来这背后的一切都和这个神秘的能量有所关联，跟着能量的轨迹，找到它的源头吧。",
		capter = 10001,
		level_id = 201002,
		scenes_pos = {
			[1] = -277,
			[2] = -17,
			[3] = -5,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100110,
		level = 1,
		finish_type = 4,
		finish_param = "control_num",
		finish_num = {
			[1] = 2010,
			[2] = 1,
		},
		finish_desc = "调查神秘的能量",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100110] = {
		id = 20100110,
		type = 1,
		stronghold_task = 0,
		name = "一触即发",
		desc = "突如其来的战斗，看来想要找到真正的原因，必须战胜眼前的敌人！",
		capter = 10001,
		level_id = 201002,
		scenes_pos = nil,
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100111,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20026,
		},
		finish_desc = "击败精英敌人防爆者",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = 3,
		lock_capter = 10001,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100111] = {
		id = 20100111,
		type = 1,
		stronghold_task = 0,
		name = "诺亚研究中心",
		desc = "这一切的原因都指向了这个终点—诺亚研究中心！看来必须要去调查一番了。",
		capter = 10001,
		level_id = 201003,
		scenes_pos = {
			[1] = -355,
			[2] = -16,
			[3] = -5,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100112,
		level = 1,
		finish_type = 6,
		finish_param = "area",
		finish_num = {
			[1] = 20002,
		},
		finish_desc = "探索诺亚研究中心",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100112] = {
		id = 20100112,
		type = 1,
		stronghold_task = 0,
		name = "通向高层",
		desc = "从能力的汇聚来看，似乎大楼顶部的能量最强，我们得找到通往楼顶的道路。",
		capter = 10001,
		level_id = 201003,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100117,
		level = 1,
		finish_type = 1,
		finish_param = "subtask_sequence",
		finish_num = {
			[1] = 20100113,
			[2] = 20100114,
			[3] = 20100115,
		},
		finish_desc = "",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100113] = {
		id = 20100113,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10001,
		level_id = 201003,
		scenes_pos = {
			[1] = -70,
			[2] = 8,
			[3] = -3,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = 20100114,
		level = 1,
		finish_type = 4,
		finish_param = "control_num",
		finish_num = {
			[1] = 2011,
			[2] = 1,
		},
		finish_desc = "寻找通往高层的线索",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100114] = {
		id = 20100114,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10001,
		level_id = 201003,
		scenes_pos = {
			[1] = -12,
			[2] = 8,
			[3] = 48,
		},
		scenes_radius = {
			[1] = 8,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = 20100115,
		level = 1,
		finish_type = 4,
		finish_param = "control_num",
		finish_num = {
			[1] = 2012,
			[2] = 1,
		},
		finish_desc = "在房间内寻找ID卡",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100115] = {
		id = 20100115,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10001,
		level_id = 201003,
		scenes_pos = {
			[1] = -70,
			[2] = 8,
			[3] = -3,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = nil,
		level = 1,
		finish_type = 6,
		finish_param = "area",
		finish_num = {
			[1] = 20004,
		},
		finish_desc = "启动电梯",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100117] = {
		id = 20100117,
		type = 1,
		stronghold_task = 0,
		name = "决战时刻",
		desc = "这一连串的罪魁祸首终于现身，看来必须亲手终结这一切了。",
		capter = 10001,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100118,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20028,
		},
		finish_desc = "抵挡怪物的进攻",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100118] = {
		id = 20100118,
		type = 1,
		stronghold_task = 0,
		name = "决战时刻",
		desc = "这一连串的罪魁祸首终于现身，看来必须亲手终结这一切了。",
		capter = 10001,
		level_id = 201004,
		scenes_pos = {
			[1] = -14,
			[2] = 0,
			[3] = 18,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100119,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20030,
		},
		finish_desc = "前往楼顶",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100119] = {
		id = 20100119,
		type = 1,
		stronghold_task = 0,
		name = "决战时刻",
		desc = "这一连串的罪魁祸首终于现身，看来必须亲手终结这一切了。",
		capter = 10001,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = nil,
		level = 1,
		finish_type = 3,
		finish_param = "kill_monster",
		finish_num = {
			[1] = 220110006,
			[2] = 1,
		},
		finish_desc = "继续前进",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = true,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100120] = {
		id = 20100120,
		type = 2,
		stronghold_task = 0,
		name = "决战时刻",
		desc = "这一连串的罪魁祸首终于现身，看来必须亲手终结这一切了。",
		capter = 10001,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 2,
		draw_type = false,
		last_task_id = nil,
		level = 1,
		finish_type = 3,
		finish_param = "kill_monster",
		finish_num = {
			[1] = 220110008,
			[2] = 2,
		},
		finish_desc = "击败%s",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100121] = {
		id = 20100121,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10001,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = nil,
		level = 1,
		finish_type = 5,
		finish_param = "player_level",
		finish_num = {
			[1] = 1,
		},
		finish_desc = "",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = 4,
		lock_capter = 10002,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100201] = {
		id = 20100201,
		type = 1,
		stronghold_task = 0,
		name = "诺亚研究中心",
		desc = "这一切的原因都指向了这个终点—诺亚研究中心！看来必须要去调查一番了。",
		capter = 10002,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 3,
		draw_type = true,
		last_task_id = 20100202,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20012,
		},
		finish_desc = "探索诺亚研究中心",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100202] = {
		id = 20100202,
		type = 1,
		stronghold_task = 0,
		name = "通向高层",
		desc = "从能力的汇聚来看，似乎大楼顶部的能量最强，我们得找到通往楼顶的道路。",
		capter = 10002,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = 20100206,
		level = 1,
		finish_type = 1,
		finish_param = "subtask_sequence",
		finish_num = {
			[1] = 20100203,
			[2] = 20100204,
			[3] = 20100205,
		},
		finish_desc = "",
		event = nil,
		reward = {
			[10101] = {
				id = 10101,
				count = 10,
			},
			[10102] = {
				id = 10102,
				count = 20,
			},
		},
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100203] = {
		id = 20100203,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10002,
		level_id = 201004,
		scenes_pos = {
			[1] = 0,
			[2] = 10,
			[3] = -30,
			[4] = -16,
			[5] = 11,
			[6] = -61,
			[7] = -52,
			[8] = 11,
			[9] = -35,
			[10] = -70,
			[11] = 10,
			[12] = -3,
		},
		scenes_radius = {
			[1] = 4,
			[2] = 4,
			[3] = 4,
			[4] = 4,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = 20100204,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20013,
		},
		finish_desc = "寻找通往高层的线索",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100204] = {
		id = 20100204,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10002,
		level_id = 201004,
		scenes_pos = {
			[1] = -53,
			[2] = 10,
			[3] = 30,
			[4] = -37,
			[5] = 10,
			[6] = 64,
			[7] = -16,
			[8] = 10,
			[9] = 59,
			[10] = 2,
			[11] = 10,
			[12] = 58,
		},
		scenes_radius = {
			[1] = 4,
			[2] = 4,
			[3] = 3,
			[4] = 3,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = 20100205,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20014,
		},
		finish_desc = "在房间内寻找ID卡",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100205] = {
		id = 20100205,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10002,
		level_id = 201004,
		scenes_pos = {
			[1] = -16,
			[2] = 10,
			[3] = 59,
			[4] = -37,
			[5] = 10,
			[6] = 64,
			[7] = -53,
			[8] = 10,
			[9] = 30,
			[10] = -70,
			[11] = 10,
			[12] = -3,
		},
		scenes_radius = {
			[1] = 4,
			[2] = 4,
			[3] = 4,
			[4] = 4,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = nil,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20033,
		},
		finish_desc = "启动电梯",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100206] = {
		id = 20100206,
		type = 1,
		stronghold_task = 0,
		name = "决战时刻",
		desc = "从能力的汇聚来看，似乎大楼顶部的能量最强，我们得找到通往楼顶的道路。",
		capter = 10002,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = nil,
		level = 1,
		finish_type = 1,
		finish_param = "subtask_sequence",
		finish_num = {
			[1] = 20100207,
			[2] = 20100208,
			[3] = 20100209,
		},
		finish_desc = "",
		event = nil,
		reward = nil,
		is_ending = true,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100207] = {
		id = 20100207,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10002,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = 20100208,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20028,
		},
		finish_desc = "前往楼顶",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100208] = {
		id = 20100208,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10002,
		level_id = 201004,
		scenes_pos = {
			[1] = -12,
			[2] = 0,
			[3] = 18,
		},
		scenes_radius = {
			[1] = 2,
		},
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = 20100209,
		level = 1,
		finish_type = 7,
		finish_param = "talk",
		finish_num = {
			[1] = 20030,
		},
		finish_desc = "继续前进",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20100209] = {
		id = 20100209,
		type = 3,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10002,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = false,
		last_task_id = nil,
		level = 1,
		finish_type = 3,
		finish_param = "kill_monster",
		finish_num = {
			[1] = 220110012,
			[2] = 1,
		},
		finish_desc = "击败%s",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20200001] = {
		id = 20200001,
		type = 1,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10003,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = nil,
		level = 1,
		finish_type = 3,
		finish_param = "kill_monster",
		finish_num = {
			[1] = 220110012,
			[2] = 1,
		},
		finish_desc = "击败%s",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[20200002] = {
		id = 20200002,
		type = 1,
		stronghold_task = 0,
		name = "",
		desc = "",
		capter = 10003,
		level_id = 201004,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = nil,
		level = 1,
		finish_type = 3,
		finish_param = "kill_monster",
		finish_num = {
			[1] = 220110012,
			[2] = 1,
		},
		finish_desc = "击败%s",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[30000001] = {
		id = 30000001,
		type = 4,
		stronghold_task = 1,
		name = "测试任务2",
		desc = "测试任务2",
		capter = 30001,
		level_id = 301001,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = nil,
		level = 1,
		finish_type = 3,
		finish_param = "kill_monster",
		finish_num = {
			[1] = 220110008,
			[2] = 5,
		},
		finish_desc = "击败%s",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
	[30000002] = {
		id = 30000002,
		type = 4,
		stronghold_task = 2,
		name = "蜂巢玩法",
		desc = "蜂巢玩法",
		capter = 30001,
		level_id = 301001,
		scenes_pos = nil,
		scenes_radius = nil,
		map_id = nil,
		map_pos = nil,
		accept_type = 1,
		draw_type = true,
		last_task_id = nil,
		level = 1,
		finish_type = 3,
		finish_param = "kill_monster",
		finish_num = {
			[1] = 220110008,
			[2] = 5,
		},
		finish_desc = "击败%s",
		event = nil,
		reward = nil,
		is_ending = false,
		lock_area = nil,
		lock_capter = nil,
		console_id = nil,
		obstacle_id = nil,
		gate_id = nil,
	},
}
