-- id                               int                              道具ID（404+套装+星级+部位id）
-- type1                            int                              道具大类
-- type2                            int                              道具子类
-- type3                            int                              道具细分（所属套装）
-- name                             lang                             道具名称
-- des                              lang                             道具描述
-- bg_des                           lang                             道具背景描述
-- item_tag                         int                              道具角标
-- item_icon                        int                              道具图标
-- item_position                    int                              质点部位
-- item_bg                          int                              道具背板
-- quality                          int                              道具品质
-- star                             int                              道具星级
-- star_max                         int                              道具星级上限
-- summax                           int                              获取上限
-- gridmax                          int                              堆叠上限
-- jump_id                          tableString[k:#seq|v:#table(jumpid=#1(int),count=#2(int))]   获取跳转
-- jump_des                         lang                             无获取途径描述
-- resolve_item                     tableString[k:#seq|v:#table(id=#1(int),count=#2(int))]   基础分解道具
-- is_resolve                       bool                             是否可手动分解
-- bag_id                           int                              所属背包
-- max_way                          int                              获取上限处理方式
-- autouse                          bool                             自使用
-- useprofit                        string                           自使用效果
-- show                             int                              获得方式展示
-- variable                         string                           关联参数
-- item_go                          tableString[k:#seq|v:#1(int)]    前往功能
-- exp                              int                              强化提供基础经验
-- slot                             int                              觉醒槽位数
-- default_level                    int                              初始等级
-- default_stage                    int                              初始等阶
-- gold                             int                              强化消耗金币

return {
	[4040111] = {
		id = 4040111,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 1,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040112] = {
		id = 4040112,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 2,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 2,
		gold = 50,
	},
	[4040113] = {
		id = 4040113,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 3,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 2,
		default_stage = 1,
		gold = 50,
	},
	[4040114] = {
		id = 4040114,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 4,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 5,
		default_stage = 2,
		gold = 50,
	},
	[4040115] = {
		id = 4040115,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 5,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 3,
		default_stage = 1,
		gold = 50,
	},
	[4040121] = {
		id = 4040121,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 1,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040122] = {
		id = 4040122,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 2,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040123] = {
		id = 4040123,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 3,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040124] = {
		id = 4040124,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 4,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040125] = {
		id = 4040125,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 5,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040131] = {
		id = 4040131,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 1,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040132] = {
		id = 4040132,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 2,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040133] = {
		id = 4040133,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 3,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040134] = {
		id = 4040134,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 4,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040135] = {
		id = 4040135,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 5,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040141] = {
		id = 4040141,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 1,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040142] = {
		id = 4040142,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 2,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040143] = {
		id = 4040143,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 3,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040144] = {
		id = 4040144,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 4,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040145] = {
		id = 4040145,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 5,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040151] = {
		id = 4040151,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 1,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040152] = {
		id = 4040152,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 2,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040153] = {
		id = 4040153,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 3,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040154] = {
		id = 4040154,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 4,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040155] = {
		id = 4040155,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 5,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040161] = {
		id = 4040161,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 1,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040162] = {
		id = 4040162,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 2,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040163] = {
		id = 4040163,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 3,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040164] = {
		id = 4040164,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 4,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040165] = {
		id = 4040165,
		type1 = 4,
		type2 = 4,
		type3 = 1,
		name = "玛雅古钱",
		des = "极致的进攻质点，可大幅提升进攻属性",
		bg_des = "极致的进攻质点，可大幅提升进攻属性",
		item_tag = nil,
		item_icon = 10001,
		item_position = 5,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040211] = {
		id = 4040211,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 1,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040212] = {
		id = 4040212,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 2,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040213] = {
		id = 4040213,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 3,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040214] = {
		id = 4040214,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 4,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040215] = {
		id = 4040215,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 5,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040221] = {
		id = 4040221,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 1,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040222] = {
		id = 4040222,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 2,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040223] = {
		id = 4040223,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 3,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040224] = {
		id = 4040224,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 4,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040225] = {
		id = 4040225,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 5,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040231] = {
		id = 4040231,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 1,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040232] = {
		id = 4040232,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 2,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040233] = {
		id = 4040233,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 3,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040234] = {
		id = 4040234,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 4,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040235] = {
		id = 4040235,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 5,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040241] = {
		id = 4040241,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 1,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040242] = {
		id = 4040242,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 2,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040243] = {
		id = 4040243,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 3,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040244] = {
		id = 4040244,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 4,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040245] = {
		id = 4040245,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 5,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040251] = {
		id = 4040251,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 1,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040252] = {
		id = 4040252,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 2,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040253] = {
		id = 4040253,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 3,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040254] = {
		id = 4040254,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 4,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040255] = {
		id = 4040255,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 5,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040261] = {
		id = 4040261,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 1,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040262] = {
		id = 4040262,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 2,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040263] = {
		id = 4040263,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 3,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040264] = {
		id = 4040264,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 4,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040265] = {
		id = 4040265,
		type1 = 4,
		type2 = 4,
		type3 = 2,
		name = "潘多拉魔盒",
		des = "极致的防御质点，可大幅提升生存能力",
		bg_des = "极致的防御质点，可大幅提升生存能力",
		item_tag = nil,
		item_icon = 10002,
		item_position = 5,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040311] = {
		id = 4040311,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 1,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040312] = {
		id = 4040312,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 2,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040313] = {
		id = 4040313,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 3,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040314] = {
		id = 4040314,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 4,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040315] = {
		id = 4040315,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 5,
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 100,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 50,
	},
	[4040321] = {
		id = 4040321,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 1,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040322] = {
		id = 4040322,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 2,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040323] = {
		id = 4040323,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 3,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040324] = {
		id = 4040324,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 4,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040325] = {
		id = 4040325,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 5,
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 200,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 100,
	},
	[4040331] = {
		id = 4040331,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 1,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040332] = {
		id = 4040332,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 2,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040333] = {
		id = 4040333,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 3,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040334] = {
		id = 4040334,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 4,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040335] = {
		id = 4040335,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 5,
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 2000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 1000,
	},
	[4040341] = {
		id = 4040341,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 1,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040342] = {
		id = 4040342,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 2,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040343] = {
		id = 4040343,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 3,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040344] = {
		id = 4040344,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 4,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040345] = {
		id = 4040345,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 5,
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 5000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 2500,
	},
	[4040351] = {
		id = 4040351,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 1,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040352] = {
		id = 4040352,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 2,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040353] = {
		id = 4040353,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 3,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040354] = {
		id = 4040354,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 4,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040355] = {
		id = 4040355,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 5,
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 8000,
		slot = 0,
		default_level = 1,
		default_stage = 1,
		gold = 4000,
	},
	[4040361] = {
		id = 4040361,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 1,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040362] = {
		id = 4040362,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 2,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040363] = {
		id = 4040363,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 3,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040364] = {
		id = 4040364,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 4,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
	[4040365] = {
		id = 4040365,
		type1 = 4,
		type2 = 4,
		type3 = 3,
		name = "万用试纸",
		des = "极致的辅助质点，可大幅提升辅助能力",
		bg_des = "极致的辅助质点，可大幅提升辅助能力",
		item_tag = nil,
		item_icon = 10003,
		item_position = 5,
		item_bg = 6,
		quality = 6,
		star = 6,
		star_max = nil,
		summax = 999999999,
		gridmax = 1,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = true,
		bag_id = 1,
		max_way = 0,
		autouse = false,
		useprofit = "",
		show = 0,
		variable = "",
		item_go = {
			[1] = 1,
			[2] = 1,
		},
		exp = 12000,
		slot = 2,
		default_level = 1,
		default_stage = 1,
		gold = 6000,
	},
}
