-- id                               int                              宝箱ID
-- bag_id                           int                              所属背包
-- drop                             int                              箱子Drop
-- droplimt                         tableString[k:#1(int)|v:#1(int)]   掉落内容限制
-- type1                            int                              道具大类
-- type2                            int                              道具子类
-- type3                            int                              道具细分
-- name                             lang                             道具名称
-- des                              lang                             道具描述
-- bg_des                           lang                             道具背景描述
-- item_tag                         int                              道具角标
-- item_icon                        string                           道具图标
-- item_bg                          int                              道具背景板
-- quality                          int                              道具品质
-- star                             int                              道具星级
-- star_max                         int                              道具星级上限
-- summax                           int                              获取上限
-- gridmax                          int                              堆叠上限
-- jump_id                          tableString[k:#seq|v:#table(jumpid=#1(int),count=#2(int))]   获取跳转
-- jump_des                         lang                             无获取途径描述
-- resolve_item                     tableString[k:#seq|v:#table(id=#1(int),count=#2(int))]   分解道具
-- is_resolve                       bool                             是否可手动分解
-- max_way                          int                              上限处理方式
-- show                             int                              获取方式展示
-- autouse                          bool                             自使用
-- useprofit                        string                           自使用效果

return {
	[201001] = {
		id = 201001,
		bag_id = 2,
		drop = 201001,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 1,
		name = "测试自选箱",
		des = "测试自选箱道具描述",
		bg_des = "测试自选箱背景描述",
		item_tag = 0,
		item_icon = "10003",
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 3,
		autouse = false,
		useprofit = "",
	},
	[201002] = {
		id = 201002,
		bag_id = 2,
		drop = 201001,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 1,
		name = "测试自选箱",
		des = "测试自选箱道具描述",
		bg_des = "测试自选箱背景描述",
		item_tag = 0,
		item_icon = "10003",
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 2,
		autouse = false,
		useprofit = "",
	},
	[201003] = {
		id = 201003,
		bag_id = 2,
		drop = 201001,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 1,
		name = "测试自选箱",
		des = "测试自选箱道具描述",
		bg_des = "测试自选箱背景描述",
		item_tag = 0,
		item_icon = "10003",
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 1,
		autouse = false,
		useprofit = "",
	},
	[201004] = {
		id = 201004,
		bag_id = 2,
		drop = 201001,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 1,
		name = "测试自选箱",
		des = "测试自选箱道具描述",
		bg_des = "测试自选箱背景描述",
		item_tag = 0,
		item_icon = "10003",
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 0,
		autouse = false,
		useprofit = "",
	},
	[201005] = {
		id = 201005,
		bag_id = 2,
		drop = 201001,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 1,
		name = "测试自选箱",
		des = "测试自选箱道具描述",
		bg_des = "测试自选箱背景描述",
		item_tag = 0,
		item_icon = "10003",
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 0,
		autouse = false,
		useprofit = "",
	},
	[201006] = {
		id = 201006,
		bag_id = 2,
		drop = 201001,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 1,
		name = "测试自选箱",
		des = "测试自选箱道具描述",
		bg_des = "测试自选箱背景描述",
		item_tag = 0,
		item_icon = "10003",
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 0,
		autouse = false,
		useprofit = "",
	},
	[201007] = {
		id = 201007,
		bag_id = 2,
		drop = 201007,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试权重随机箱",
		des = "测试权重随机箱道具描述",
		bg_des = "测试权重随机箱背景描述",
		item_tag = 0,
		item_icon = "10003",
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 0,
		autouse = false,
		useprofit = "",
	},
	[201008] = {
		id = 201008,
		bag_id = 2,
		drop = 201007,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试权重随机箱",
		des = "测试权重随机箱道具描述",
		bg_des = "测试权重随机箱背景描述",
		item_tag = 0,
		item_icon = "10003",
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 0,
		autouse = false,
		useprofit = "",
	},
	[201009] = {
		id = 201009,
		bag_id = 2,
		drop = 201007,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试权重随机箱",
		des = "测试权重随机箱道具描述",
		bg_des = "测试权重随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 0,
		autouse = false,
		useprofit = "",
	},
	[201010] = {
		id = 201010,
		bag_id = 2,
		drop = 201007,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试权重随机箱",
		des = "测试权重随机箱道具描述",
		bg_des = "测试权重随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 0,
		autouse = false,
		useprofit = "",
	},
	[201011] = {
		id = 201011,
		bag_id = 2,
		drop = 201007,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试权重随机箱",
		des = "测试权重随机箱道具描述",
		bg_des = "测试权重随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 1,
		autouse = false,
		useprofit = "",
	},
	[201012] = {
		id = 201012,
		bag_id = 2,
		drop = 201007,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试权重随机箱",
		des = "测试权重随机箱道具描述",
		bg_des = "测试权重随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 1,
		autouse = false,
		useprofit = "",
	},
	[201013] = {
		id = 201013,
		bag_id = 2,
		drop = 201007,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试权重随机箱",
		des = "测试权重随机箱道具描述",
		bg_des = "测试权重随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 1,
		autouse = false,
		useprofit = "",
	},
	[201014] = {
		id = 201014,
		bag_id = 2,
		drop = 201014,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试概率随机箱",
		des = "测试概率随机箱道具描述",
		bg_des = "测试概率随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 1,
		autouse = false,
		useprofit = "",
	},
	[201015] = {
		id = 201015,
		bag_id = 2,
		drop = 201014,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试概率随机箱",
		des = "测试概率随机箱道具描述",
		bg_des = "测试概率随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 5,
		quality = 5,
		star = 5,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 1,
		autouse = false,
		useprofit = "",
	},
	[201016] = {
		id = 201016,
		bag_id = 2,
		drop = 201014,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试概率随机箱",
		des = "测试概率随机箱道具描述",
		bg_des = "测试概率随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 1,
		quality = 1,
		star = 1,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 2,
		autouse = false,
		useprofit = "",
	},
	[201017] = {
		id = 201017,
		bag_id = 2,
		drop = 201014,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试概率随机箱",
		des = "测试概率随机箱道具描述",
		bg_des = "测试概率随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 2,
		quality = 2,
		star = 2,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 2,
		autouse = false,
		useprofit = "",
	},
	[201018] = {
		id = 201018,
		bag_id = 2,
		drop = 201014,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试概率随机箱",
		des = "测试概率随机箱道具描述",
		bg_des = "测试概率随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 3,
		quality = 3,
		star = 3,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 2,
		autouse = false,
		useprofit = "",
	},
	[201019] = {
		id = 201019,
		bag_id = 2,
		drop = 201014,
		droplimt = {
			[1] = 1,
		},
		type1 = 2,
		type2 = 1,
		type3 = 2,
		name = "测试概率随机箱",
		des = "测试概率随机箱道具描述",
		bg_des = "测试概率随机箱背景描述",
		item_tag = 1,
		item_icon = "10003",
		item_bg = 4,
		quality = 4,
		star = 4,
		star_max = 5,
		summax = 999,
		gridmax = 999,
		jump_id = {
			[1] = {
				jumpid = 2,
				count = 1,
			},
			[2] = {
				jumpid = 2,
				count = 2,
			},
		},
		jump_des = "暂无获取道具方式，只能通过gm命令发放",
		resolve_item = {
			[1] = {
				id = 10102,
				count = 100,
			},
		},
		is_resolve = false,
		max_way = 0,
		show = 2,
		autouse = false,
		useprofit = "",
	},
}
