addRequire("AutoRequireConfig")
addRequire("RequireConfig")
addRequire("RequireUI")

--框架
addRequire("framework/ui/BaseComponent")
addRequire("framework/ui/BaseWindow")
addRequire("framework/ui/BaseWindowExtend")
addRequire("framework/ui/UIConfig")
addRequire("framework/ui/UIManager")
addRequire("framework/ui/UIGlobal")
addRequire("framework/ui/UIRequire")
addRequire("framework/ui/UIUtil")
addRequire("framework/messager/Msg")
addRequire("framework/messager/MsgCenter")
addRequire("framework/messager/Messager")
addRequire("framework/utility/TableExtend")

--基础
addRequire("EngineDefine")
addRequire("Class")
addRequire("Global")
addRequire("Prefab")
addRequire("ObjectManager")
addRequire("Define")