addUIRequire("component/HintCommon")

addUIRequire("component/Loading")
addUIRequire("component/DamageFont")
addUIRequire("component/MonsterHp")
addUIRequire("component/TopBanner")
addUIRequire("component/ItemTipsWindow")

addUIRequire("component/Battle/FocusUIKotori")
addUIRequire("component/Battle/GunProgress")

addUIRequire("component/TestAssetItem")
addUIRequire("window/TestAssetWindow")


addUIRequire("window/NotifyWindow")
addUIRequire("window/LoadSceneWindow")

addUIRequire("window/LoginWindow")
addUIRequire("window/MainWindow")
addUIRequire("window/BattleWindow")
addUIRequire("window/BattleClearWindow")
addUIRequire("window/battle/BattleTargetWidget")
addUIRequire("window/battle/BattleTargetSingleWidget")
addUIRequire("window/battle/BattleHeadInfo")
addUIRequire("window/battle/BattleHeadWidget")
addUIRequire("window/battle/BattleTaskMarker")
addUIRequire("window/battle/BattleGMWindow")
addUIRequire("window/SelectLevelWindow")
addUIRequire("window/BattlePauseWindow")
addUIRequire("window/DialogWindow")
addUIRequire("window/NarratorWindow")
addUIRequire("window/BlockbusterWindow")
addUIRequire("window/VideoWindow")
addUIRequire("window/BossEnterShowWindow")
addUIRequire("window/LevelTransmitWindow")
addUIRequire("window/PositionTransmitWindow")

addUIRequire("window/bag/BagMainWindow")
addUIRequire("window/bag/Bag_ItemCom")
addUIRequire("window/bag/Bag_NodeTap")
addUIRequire("window/bag/Bag_NodeSell")
addUIRequire("window/bag/Bag_NodeItem")

addUIRequire("window/bag/ItemInfoWindow")
addUIRequire("window/bag/ItemInfoWindow_NodeInfo")
addUIRequire("window/bag/ItemInfoWindow_NodeItem")
addUIRequire("window/bag/ItemInfoWindow_NodeSpecial")
addUIRequire("window/bag/ItemInfoWindow_NodeDetail")
addUIRequire("window/bag/ItemInfoWindow_NodeGet")
addUIRequire("window/bag/ItemInfoWindow_NodeUse")
addUIRequire("window/bag/ItemBoxUseWindow")
addUIRequire("window/bag/ItemBoxDetialWindow")
addUIRequire("window/ItemInfoShowWindow")

--关卡/挂机系统
addUIRequire("window/chapter/BoxRewardWindow")
addUIRequire("window/chapter/TaskRewardWindow")
addUIRequire("window/chapter/TaskDetailsWindow")
addUIRequire("window/chapter/ChapterWindow")
addUIRequire("window/chapter/ChapterDetailWindow")
addUIRequire("window/chapter/ChapterTopInfoWindow")
addUIRequire("window/chapter/ChapterTopShopWindow")
addUIRequire("window/chapter/ChapterTopAreaWindow")
addUIRequire("window/chapter/ChapterSearchConfirmWindow")
addUIRequire("window/chapter/ChapterSearchSpeedUpWindow")
addUIRequire("window/chapter/ChapterSearchResultWindow")
addUIRequire("window/chapter/ChapterSearchRewardWindow")
addUIRequire("window/chapter/ChapterSearchSpeedUpWindow")
addUIRequire("window/chapter/ChapterSearchEventWindow")
addUIRequire("window/chapter/ChapterGarrisonWindow")
addUIRequire("window/chapter/ChapterGarrisonFormationWindow")
addUIRequire("window/chapter/ChapterGarrisonRewardWindow")
addUIRequire("window/chapter/ChapterTaskWindow")
addUIRequire("window/chapter/EventCheckWindow")

--任务（常规）系统
addUIRequire("window/task/TaskWindow")

--阵容界面
addUIRequire("window/formation/HeroSelectWindow")
addUIRequire("window/formation/FormationWindow")

addUIRequire("window/hero/panel/HeroBasePanel")
addUIRequire("window/hero/panel/HeroHeadPanel")
addUIRequire("window/hero/panel/HeroUnlockPanel")
addUIRequire("window/hero/panel/HeroOverviewPanel")
addUIRequire("window/hero/panel/HeroMenuPanel")
addUIRequire("window/hero/panel/HeroSwitchPanel")
addUIRequire("window/hero/panel/HeroLevelPanel")
addUIRequire("window/hero/panel/HeroLevelupPanel")
addUIRequire("window/hero/panel/HeroStarPanel")
addUIRequire("window/hero/panel/HeroSkillPanel")
addUIRequire("window/hero/HeroStageupWindow")
addUIRequire("window/hero/HeroStarupWindow")
addUIRequire("window/hero/HeroWindow")

addUIRequire("window/gm/GMWindow")
addUIRequire("window/gm/BattleHeroDebugWindow")

addUIRequire("window/EquipSuitInBagWindow")

addUIRequire("window/equip/EquipWindow")
addUIRequire("window/equip/Equip_OwnEquip")
addUIRequire("window/equip/Equip_Equip")
addUIRequire("window/equip/Equip_PopupDetail")
addUIRequire("window/equip/EquipOwn_Change")
addUIRequire("window/equip/EquipOwn_EquipDetail")
addUIRequire("window/equip/EquipOwn_ChangePlace")
addUIRequire("window/equip/EquipOwn_ChangeSuit")
addUIRequire("window/equip/Equip_ItemCell")
addUIRequire("window/equip/Equip_EquipedCell")

addUIRequire("window/equip/EquipSuitWindow")
addUIRequire("window/equip/EquipSuit_Suit")
addUIRequire("window/equip/EquipSuit_Equip")
addUIRequire("window/equip/EquipSuit_Details")
addUIRequire("window/equip/EquipSuit_Rename")

addUIRequire("window/equip/EquipGrowWindow")
addUIRequire("window/equip/EquipGrow_Details")
addUIRequire("window/equip/EquipGrow_Intensify")
addUIRequire("window/equip/EquipGrow_Awaken")
addUIRequire("window/equip/EquipGrow_Break")
addUIRequire("window/equip/EquipGrow_BaseInfo")
addUIRequire("window/equip/EquipGrow_AwakenSuccess")

addUIRequire("window/equip/EquipInfoPopupWindow")
addUIRequire("window/equip/EquipBreakPopup")
addUIRequire("window/equip/EquipStageupWindow")

addUIRequire("window/equip/EquipUsedWindow")
addUIRequire("window/equip/EquipOwnChangeSuitPopup")

addUIRequire("window/EquipInfoWindow")
addUIRequire("window/JumpGetWindow")

addUIRequire("window/ship/ShipWindow")
addUIRequire("window/ship/ShipPopup_Item")
addUIRequire("window/ship/ShipPopup_Card")
addUIRequire("window/ship/ShipPopup")

addUIRequire("window/ship/ShipTokenWindow")
addUIRequire("window/ship/ShipToken_Bag")
addUIRequire("window/ship/ShipToken_Cell")
addUIRequire("window/ship/ShipToken_Details")
addUIRequire("window/ship/ShipToken_SuccessPopup")


addUIRequire("window/ship/ShipScienceWindow")
addUIRequire("window/ship/ShipScience_Cell")
addUIRequire("window/ship/ShipScience_Details")
addUIRequire("window/ship/ShipMakeWindow")
addUIRequire("window/ship/ShipMake_Room")
addUIRequire("window/ship/ShipMake_RoomDetail")
addUIRequire("window/ship/ShipMake_SpeedPopup")
addUIRequire("window/ship/ShipMake_DetailPopup")
addUIRequire("window/ship/ShipMake_RecievePopup")

addUIRequire("window/ship/ShipPresenceWindow")
addUIRequire("window/ship/ShipPresence_Heros")
addUIRequire("window/ship/ShipPresenceSelectWindow")
addUIRequire("window/ship/ShipPresence_HeroTipPopup")


addUIRequire("window/MultiFightWaitingWindow")
