-- @brief: UI消息定义
-- @version: 1.0.0
-- @author lanqibo
-- All rights reserved
Msg = {
    HINT_COMMON = "HINT_COMMON",    --全局文字小提示
    NOTIFY = "NOTIFY", --全局弹窗
    OPEN_WINDOW = "OPEN_WINDOW", --全局打开一个UI
    OPEN_WINDOW_FINISH = "OPEN_WINDOW_FINISH", --全局打开一个UI后
    CLOSE_WINDOW = "CLOSE_WINDOW", --全局关闭一个UI
    CLOSE_WINDOW_FINISH = "CLOSE_WINDOW_FINISH", --全局关闭一个UI后
    SHOW_TOPBANNER = "SHOW_TOPBANNER", --显示隐藏TopBanner
    SHOW_LOADING = "SHOW_LOADING", --显示加载提示
    HIDE_LOADING = "HIDE_LOADING", --隐藏加载提示

    LOCK_SCREEN = "LOCK_SCREEN", --锁屏

    LOAD_SCENE_PROGRESS = "LOAD_SCENE_PROGRESS", --场景加载进度

    SCREEN_DARK = "SCREEN_DARK",        --全局屏幕变暗

    BATTLE_HP_CHANGE = "BATTLE_HP_CHANGE",  --战斗血量变化

    BATTLE_ADD_ROLE = "BATTLE_ADD_ROLE",  --产生角色(主角、怪物)
    BATTLE_ADD_ACTOR = "BATTLE_ADD_ACTOR",  --产生主角
    BATTLE_ADD_MONSTER = "BATTLE_ADD_MONSTER",  --产生怪物

    BATTLE_REMOVE_ROLE = "BATTLE_REMOVE_ROLE",  --产生角色(主角、怪物)
    BATTLE_REMOVE_ACTOR = "BATTLE_REMOVE_ACTOR",  --移除角色
    BATTLE_REMOVE_MONSTER = "BATTLE_REMOVE_MONSTER",  --移除怪物

    BATTLE_SHOW_TARGET = "BATTLE_SHOW_TARGET",
    BATTLE_SPECIALCAMERA = "BATTLE_SPECIALCAMERA",
    BATTLE_COMBO_COUNT = "BATTLE_COMBO_COUNT",
    BATTLE_CHAIN_GROUP = "BATTLE_CHAIN_GROUP",
    BATTLE_CHANGE_ACTOR = "BATTLE_CHANGE_ACTOR",
    BATTLE_ON_CHANGE_ACTOR = "BATTLE_ON_CHANGE_ACTOR",  --主角换人
    BATTLE_SHOW_LEVEL_TIP = "BATTLE_SHOW_LEVEL_TIP", --显示关卡提示
    BATTLE_SHOW_LEVEL_EVENT = "BATTLE_SHOW_LEVEL_EVENT", --显示关卡事件
    BATTLE_SHOW_PASS_CONDTION = "BATTLE_SHOW_PASS_CONDTION", --显示关卡通关条件
    BATTLE_PASS_CHECKPOINT = "BATTLE_PASS_CHECKPOINT",--通过关卡
    BATTLE_START = "BATTLE_START", --角色播放完入场动画
    BATTLE_ROLE_DEAD = "BATTLE_ROLE_DEAD",      --怪物死亡
    BATTLE_ACTIVE_ALL_UI  = "BATTLE_ACTIVE_ALL_UI",  --战斗所有UI 控制
    BATTLE_ACTIVE_LOGIC   = "BATTLE_ACTIVE_LOGIC",   --战斗逻辑

    BATTLE_SHOW_CONNECT   = "BATTLE_SHOW_CONNECT",   --显示操作台控制按钮
    BATTLE_HIDE_CONNECT   = "BATTLE_HIDE_CONNECT",   --隐藏控制台操作按钮
    BATTLE_CONSOLE_STATE_CHANGE = "BATTLE_CONSOLE_STATE_CHANGE",   --操作台状态变更
    
    BATTLE_WINDOW_STATE = "BATTLE_WINDOW_STATE",    --战斗界面状态变化

    BATTLE_USERUI_OPEN = "BATTLE_USERUI_OPEN",    --战斗自定义UI 开
    BATTLE_USERUI_CLOSE = "BATTLE_USERUI_CLOSE",    --战斗自定义UI 开

    BATTLE_POWER_UPDATE   = "BATTLE_POWER_UPDATE",   --能量槽刷新
    BATTLE_POWER_POINT = "BATTLE_POWER_POINT",       --能量点获得
    BATTLE_POWER_FULLTIP  = "BATTLE_POWER_FULLTIP",   --能量槽溢出提示

    BATTLE_CHANGE_HANDLE_STATE = "BATTLE_CHANGE_HANDLE_STATE", --切换英雄操作状态

    BATTLE_GAS_UPDATE   = "BATTLE_GAS_UPDATE",   --怒气槽刷新

    BATTLE_CONSOLE_LOCATION_CREATE = "BATTLE_CONSOLE_LOCATION_CREATE",    --操作台指引
    BATTLE_ADD_ENTITY = "BATTLE_ADD_ENTITY",    --- 增加表现实例
    BATTLE_REMOVE_ENTITY = "BATTLE_REMOVE_ENTITY",    --- 删除表现实例
    BATTLE_REMOVE_PHYSICS_ENTITY = "BATTLE_REMOVE_PHYSICS_ENTITY",    --- 删除表现实例
    BATTLE_CHANGE_MAIN_HERO = "BATTLE_CHANGE_MAIN_HERO",    --- 战斗更换主控英雄
    BATTLE_SET_SUPER_SPACE = "BATTLE_SET_SUPER_SPACE",    --- 战斗设置领域

    BATTLE_ATTACK_TYPE_CHANGE = "BATTLE_ATTACK_TYPE_CHANGE",  --攻击按钮类型变化

    BATTLE_EXIT = "BATTLE_EXIT",    --- 战斗退出
    BATTLE_REFRESH_MAIN_HERO_VIEW = "BATTLE_REFRESH_MAIN_HERO_VIEW",    --- 战斗刷新主控英雄视图
    BATTLE_MONSTER_DROP = "BATTLE_MONSTER_DROP",--关卡怪物掉落
    BATTLE_BOX_DROP = "BATTLE_BOX_DROP",--关卡宝箱奖励
    BATTLE_OBSTACLE_DROP = "BATTLE_OBSTACLE_DROP",--关卡障碍物掉落
    BATTLE_OBSTACLE_DEAD = "BATTLE_OBSTACLE_DEAD",--关卡障碍物死亡
    BATTLE_PLAY_GET_REWARD_EFFECT = "BATTLE_PLAY_GET_REWARD_EFFECT",--获得奖励特效
    DIALOG_SHOW = "DIALOG_SHOW", --对话显示
    DIALOG_HIDE = "DIALOG_HIDE", --对话关闭
    NARRATOR_TEXT_REFRESH          = "NARRATOR_TEXT_REFRESH", --旁白信息更新
    BATTLE_OBSTACLE_REWARD = "BATTLE_OBSTACLE_REWARD",    --障碍奖励显示
    FORMATION_UPDATE   = "FORMATION_UPDATE", --阵容数据更新
    CHAPTER_CONSOLE_STATUS_CHANGE = "CHAPTER_CONSOLE_STATUS_CHANGE",      --操作台状态变更
    CHAPTER_TASK_STATUS_CHANGE  = "CHAPTER_TASK_STATUS_CHANGE", --任务状态变更
    CHAPTER_TASK_RECV_REWARD    = "CHAPTER_TASK_RECV_REWARD", --领取任务奖励
    CHAPTER_TASK_ACCEPTED  = "CHAPTER_TASK_ACCEPTED", --任务接取
    CHAPTER_BRANCH_TASK_STATUS_CHANGE = "CHAPTER_BRANCH_TASK_STATUS_CHANGE", --支线任务状态变更

    CHAPTER_SEARCH_REFRESH = "CHAPTER_SEARCH_REFRESH",          --章节探索状态刷新
    CHAPTER_FORMATION_REFRESH = "CHAPTER_FORMATION_REFRESH",    --章节阵容状态刷新

    TASK_REFRESH = "TASK_REFRESH",                              --任务刷新

    BAG_UPDATE_ITEMDATA    =   "BAG_UPDATE_ITEMDATA",     --刷新背包所有道具信息
    BAG_UPDATE_SELLNODE    =   "BAG_UPDATE_SELLNODE",     --刷新分解出售界面
    BAG_UPDATE_CLOSESELLBTN   =   "BAG_UPDATE_CLOSESELLBTN",    --关闭分页界面的分解出售按钮
    BAG_UPDATE_SELLCONTENT =   "BAG_UPDATE_SELLCONTENT",      --刷新出售界面标题和描述
    BAG_UPDATE_SORTLIST    =   "BAG_UPDATE_SORTLIST",     --根据排序刷新道具排列
    BAG_UPDATE_CHOICEUSABLEITEM    =   "BAG_UPDATE_CHOICEUSABLEITEM", --刷新默认选中道具
    BAG_UPDATE_MOVENODES   =   "BAG_UPDATE_MOVENODES",    --分页 道具 出售节点移动
    BAG_INIT_ITEMTIPS      =   "BAG_INIT_ITEMTIPS",       --初始化获得道具界面
    BAG_UPDATE_ONEITEM     =   "BAG_UPDATE_ONEITEM",      --刷新背包单个道具信息
    BAG_UPDATE_OPENTAPID   =   "BAG_UPDATE_OPENTAPID",    --刷新背包页签
    BAG_UPDATE_ITEMOWNCOUNT=   "BAG_UPDATE_ITEMOWNCOUNT", --刷新当前背包中拥有种类个数

    ITEMDATA_UPDATE        =   "ITEMDATA_UPDATE",               --道具数据刷新
    MONEY_UPDATE           =   "MONEY_UPDATE",                  --金币钻石等经济刷新
    ITEM_SHOWINFO          =    "ITEM_SHOWINFO",                --打开查看一个道具的基础信息


    ITEMTIPS        =   "ITEMTIPS",     --全局打开道具提示界面（分解，获得）

    LOGIN_ACCOUNT_SUCCESS   = "loginAccountSuccess",
    LOGIN_CONNECT_SERVER    = "LOGIN_CONNECT_SERVER",
    LOGIN_ENTER_GAME        = "LOGIN_ENTER_GAME",
    RE_LOGIN_ENTER_GAME     = "RE_LOGIN_ENTER_GAME",
    GAME_SERVER_DISCONNECT  = "GAME_SERVER_DISCONNECT",
    GAME_SERVER_FAIL        = "GAME_SERVER_FAIL",
    GAME_SERVER_RECONNECT   = "GAME_SERVER_RECONNECT",

    EQUIP_INIT_ASSETS        = "EQUIP_INIT_ASSETS",               --初始化质点预制件
    EQUIP_CHANGEPLACE_SORT   = "EQUIP_CHANGEPLACE_SORT",          --刷新质点排序方式
    EQUIP_OPEN_SELECTSUIT    = "EQUIP_OPEN_SELECTSUIT",           --打开套装筛选界面
    EQUIP_UPDATE_SHOWEQUIPS   = "EQUIP_UPDATE_SHOWEQUIPS",          --筛选套装后 刷新质点显示
    EQUIP_SHOW_EQUIPINFO      = "EQUIP_SHOW_EQUIPINFO",             --显示选中信息
    EQUIP_CHANGEPLACE_PLACE  = "EQUIP_CHANGEPLACE_PLACE",         --筛选显示的位置
    EQUIP_UPDATE_EQUIPDATAS   = "EQUIP_UPDATE_EQUIPDATAS",          --数据更改 刷新当前质点界面
    

    EQUIP_SUIT_CHANGE        = "EQUIP_SUIT_CHANGE",               --改变选中套装
    EQUIP_SUIT_RENAMESHOW    = "EQUIP_SUIT_RENAMESHOW",           --打开修改套装名字弹框
    EQUIP_SUIT_UPDATESUITS   = "EQUIP_SUIT_UPDATESUITS",          --刷新当前的套装列表

    EQUIP_GROW_LOOK          = "EQUIP_GROW_LOOK",                  --质点培养界面 浏览质点
    EQUIP_GROW_EQUIPDATA     = "EQUIP_GROW_EQUIPDATA",             --质点培养界面 初始化质点数据
    EQUIP_GROW_SHOWAWAKEN    = "EQUIP_GROW_SHOWAWAKEN",            --质点培养界面 显示质点觉醒成功界面
    EQUIPGROW_CHANGE_NODESTATE = "EQUIPGROW_CHANGE_NODESTATE",    --质点培养界面 改变节点显示
    EQUIP_AWAKESLOT         = "EQUIP_AWAKESLOT",                    --质点觉醒槽位 刷新槽位id

    SHIP_NODECHANGE          = "SHI_NODECHANGE",              --基建 信物界面 节点改变
    SHIP_SHOWTOKEN           = "SHIP_SHOWTOKEN",              --基建 信物界面 查看信物详细
    SHIP_TALENT_UPDATECELL   = "SHIP_TALENT_UPDATECELL",       --基建 科技界面 刷新所有科技点UI
    SHIP_MAKE_UPDATEROOMDATA = "SHIP_MAKE_UPDATEROOMDATA",      --基建 建筑界面 刷新建筑信息
    SHIP_MAINATTRS           = "SHIP_MAINATTRS",                --基建 刷新总属性
}

